name: Feature Change
description: Request an change in the feature
title: "[Feature Change]: "
labels: ["product", "feature-change"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to request a change in the feature.
  - type: textarea
    id: description
    attributes:
      label: Description
      description: "Brief description of the existing feature that is subject to the change request. You can also attach files if needed."
    validations:
      required: true
  - type: textarea
    id: desired-change
    attributes:
      label: Desired Change
      description: "Detailed description of the proposed change."
    validations:
      required: true
  - type: textarea
    id: rationale
    attributes:
      label: Rationale
      description: "Explanation of why this change is necessary or beneficial."
  - type: textarea
    id: expected-benefits
    attributes:
      label: Expected Benefits
      description: "Anticipated improvements or benefits resulting from the change, such as enhanced functionality, performance improvements, or user satisfaction."
    validations:
      required: true
  - type: textarea
    id: impact-analysis
    attributes:
      label: Impact Analysis
      description: "Analysis of the change's potential impact on other features, system performance, or users. Include any negative impacts if applicable."
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: |
        Critical: For issues that need to be addressed right away due to their impact on operations or severe user experience degradation.
        High: Applies to issues that significantly affect functionality or performance and should be resolved in the next release cycle.
        Medium: For issues that have a moderate impact and should be fixed after high-priority issues are addressed.
        Low: Used for minor issues that have little impact on functionality or user experience, to be addressed as time allows.
      options:
        - Critical (priority-critical)
        - High (priority-high)
        - Medium (priority-medium)
        - Low (priority-low)
      default: 0
    validations:
      required: true
  - type: textarea
    id: estimated-effort
    attributes:
      label: Estimated Effort
      description: "Optional; initial estimate of the effort required to implement the change, if known."
      placeholder: "e.g., 40 man-hours, 2 weeks"
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      # description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
