name: Tests and Coverage Check For Pull Requests

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Bun
        run: |
          curl -fsSL https://bun.sh/install | bash
          echo "$HOME/.bun/bin" >> $GITHUB_PATH

      - name: Verify Bun installation
        run: bun --version

      - name: Install dependencies with Bun
        run: bun install

      - name: Check coverage threshold
        run: bun run test
